name: animated_neumorphic
description: A Flutter package that contains Neumorphismic theme Container that animates implicity by change values. Easy to use, just like Flutter's built-in Animated widget.
version: 0.2.0
homepage: https://krgm4d.dev
repository: https://github.com/Kurogoma4D/animated_neumorphic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
